In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,1.2,"1"])
print(arr)
print(type(arr)) # type obyektin tipini gosterir
print(arr.dtype) # (data type) massivdeki elemntlerin tipini gosterir

['1' '2' '3' '4' '1.2' '1']
<class 'numpy.ndarray'>
<U32


In [4]:
#burda dtype parametrden istifade ederek, elementleri istediyimiz tipde yaza bilerik
arr = np.array([1,2,3,1.2,"1"], dtype=float)
print(arr)
print(type(arr)) # type obyektin tipini gosterir
print(arr.dtype) # (data type) massivdeki elemntlerin tipini teyin edir

[1.  2.  3.  1.2 1. ]
<class 'numpy.ndarray'>
float64


In [5]:
arr = np.array([1,2,3,1.2,"1",[1,2,3]],dtype=object) #burda elementlerin tipini object'de cevirdik, sebeb ise massivin icine yazdigimiz ferqli tipler oldugu kimi qalir
print(list(arr)) # List formatında çap edirik ki, vergüllərlə görünsün

[1, 2, 3, 1.2, '1', [1, 2, 3]]


In [6]:
l=[1,"2",1.2,[1,2]] # bu listdir, massivden ferqli olaraq, elementleri oldugu tipde saxlayir
print(type(l),"\n") # type obyektin tipini gosterir
print(type(l[0]),'\n') # burda indeksi vererek elementin tipine tapiriq
for i in l: # her bir elementin tipine baxmaq ucun for dovrude yaza bilerik
  print(type(i))

<class 'list'> 

<class 'int'> 

<class 'int'>
<class 'str'>
<class 'float'>
<class 'list'>


In [7]:
arr1 = np.array([1,2,3,1.2]) # massiv float tipindedi
arr1

array([1. , 2. , 3. , 1.2])

In [8]:
arr1[3] # massivdeki indeksi 3 olan elementi cagirdiq

np.float64(1.2)

In [9]:
print(arr1[1:3]) # 1. ve 2. indeksli elemntleri cagirdiq
print(list(arr1[1:3])) # burda ise list formatinda cap edirikki verguller gorsensin

[2. 3.]
[np.float64(2.0), np.float64(3.0)]


In [10]:
print(arr1.ndim) # Massivin ölçülərini (dimensions) göstərir. Yəni, massiv neçəölçülüdür (1D, 2D, 3D və s.)

1


In [11]:
print(arr1.shape) # Massivin ölçüləri (hər bir ölçünün uzunluğu) haqqında məlumat verir. Yəni, hər bir ölçüdə neçə elementin olduğunu göstərir.

(4,)


In [12]:
print(arr1.size) # massivdəki ümumi elementlərin sayını verir

4


In [13]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
print(arr2[1,2]) # burda setir sutun indeksi vererek element cixardiriq
print(arr2[2,2])
print(arr2[-2,0])
print(arr2[:,-1])

6
9
7
[ 3  6  9 12]


In [15]:
arr2.ndim # massivin nece olculu oldugunu gosterir 2D

2

In [16]:
arr2.shape # massivin formasini gosterir(setir,sutun)

(4, 3)

In [17]:
arr2.size # massivdeki elementlerin sayini verir

12

In [18]:
arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]])
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [19]:
print(arr3[1,0,3],"\n")
print(arr3[:,:,-1],"\n")
print(arr3[1,:,1:3],"\n")
print([arr3[1,1,-1],arr3[2,0,-1]])

12 

[[ 4  8]
 [12 16]
 [20 24]] 

[[10 11]
 [14 15]] 

[np.int64(16), np.int64(20)]


In [20]:
arr3[1,1,1:3]

array([14, 15])

In [21]:
arr3.ndim

3

In [22]:
arr3.shape #(blok,setir,sütun)

(3, 2, 4)

In [23]:
arr3.size

24

In [24]:
arr4 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,24,25]],[[26,27,28,29],[30,31,32,33]]], dtype = str)
# dtype=str yazaraq butun elementler string(metn) formatinda olur
arr4

array([[['1', '2', '3', '4'],
        ['5', '6', '7', '8']],

       [['9', '10', '11', '12'],
        ['13', '14', '15', '16']],

       [['17', '18', '19', '20'],
        ['21', '22', '24', '25']],

       [['26', '27', '28', '29'],
        ['30', '31', '32', '33']]], dtype='<U2')

In [25]:
type(arr4)

numpy.ndarray

In [26]:
arr4.dtype

dtype('<U2')

In [27]:
arr4.ndim #3D massiv

3

In [28]:
arr4.shape #(blok,setir,sütun)

(4, 2, 4)

In [29]:
arr4.size

32

In [30]:
arr5 = np.ones((3,5,3))
arr5

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [31]:
arr6 = np.zeros((2,5))
arr6

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
arr7 = np.full((3,4,5),9)
arr7

array([[[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]],

       [[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]],

       [[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]]])

In [33]:
arr8 = np.eye((3),dtype=str) # bu iki funksiya kvadrat vahid matris yaradir (eye,identity)
arr9 = np.identity((9),dtype=str) #identity'de yalniz kvadrat vahid matris yaratmaq olur
# eye'in ise elave parametrleri var
print(arr8,"\n")
print(arr9)

[['1' '' '']
 ['' '1' '']
 ['' '' '1']] 

[['1' '' '' '' '' '' '' '' '']
 ['' '1' '' '' '' '' '' '' '']
 ['' '' '1' '' '' '' '' '' '']
 ['' '' '' '1' '' '' '' '' '']
 ['' '' '' '' '1' '' '' '' '']
 ['' '' '' '' '' '1' '' '' '']
 ['' '' '' '' '' '' '1' '' '']
 ['' '' '' '' '' '' '' '1' '']
 ['' '' '' '' '' '' '' '' '1']]


In [34]:
arr10 = np.arange(1,10,3) #(başlanğıc,son-1,addım)
arr10

array([1, 4, 7])

In [35]:
reshape_arr10 = arr10.reshape(1,3) #(setir,sutun) bu funksiya massivin formasini deyismek ucundur
print(reshape_arr10,"\n")
print("Massivin Ölçüsü:",reshape_arr10.ndim,"\n")
print('Forması:',reshape_arr10.shape,'\n')
print('Element sayı:',reshape_arr10.size)

[[1 4 7]] 

Massivin Ölçüsü: 2 

Forması: (1, 3) 

Element sayı: 3


In [36]:
arr11 = np.linspace(1,10,13) #(başlanğıc,son,eded sayı) generating linearly spaced values - xətti məsafəli dəyərlər yaratmaq
d = np.diff(arr11)[0] #diff funksiyasi ededler arasindaki ferqi gosterir
print(f"Elemnlər arasındaki fərq:{d:.2f}",'\n',arr11) # burda f-string sintaksisinden istifade edirem

Elemnlər arasındaki fərq:0.75 
 [ 1.    1.75  2.5   3.25  4.    4.75  5.5   6.25  7.    7.75  8.5   9.25
 10.  ]


In [37]:
arr12 = np.random.randint(1,100,10) #(başlanğıc,son-1,təsadüfi tam ədəd seçilir)
print(arr12)
print(arr12.shape)

[33 30 59 37 63 86 65 77 28 33]
(10,)


In [38]:
arr13 = arr12.reshape(2,5)
print(arr13)
arr13.shape

[[33 30 59 37 63]
 [86 65 77 28 33]]


(2, 5)

In [39]:
arr14 = np.random.randint(1,100,(6,7)) # (6,7) ölçülü massivə 1-100 aralığında təsadüfi ədədlər yaradır
print(arr14)

[[60 24 65 54 37 70 43]
 [91 69 92 80 25 24 26]
 [59 90  2 95 20 75 50]
 [25 61 35 70 24 40 66]
 [12 56 94 99 90 82 55]
 [76 47 94 11 55 98 45]]


In [40]:
arr15 = np.random.rand(3,4) #(3,4) ölçülü massivə 0-1 aralığında float tipində ədədlər yaradır
arr15

array([[0.56250806, 0.98213235, 0.46225714, 0.11051266],
       [0.68014668, 0.46059909, 0.13939806, 0.50753579],
       [0.34053576, 0.7314712 , 0.78087306, 0.25348553]])